apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-2-mongodb-mongo-express  # Updated name to comply with naming rules
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongodb
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-2-mongodb-mongo-express-secret  # Ensure this matches your updated secret name
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-2-mongodb-mongo-express-secret  # Ensure this matches your updated secret name
              key: password
---
apiVersion: v1
kind : Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017